In [1]:
import numpy as np

In [2]:
def optimal_value(capacity, weights, values):
    value = 0.
    
    prices = values[0, :] / values[1, :]
    values = 
    
    for item_num in range(values.shape[0]):
        

    return value

SyntaxError: invalid syntax (2108669232.py, line 5)

In [8]:
capacity, weights = 3, 50
values = np.array([[60, 20], [100, 50], [120, 30]])

In [31]:
prices.argsort()

array([[1, 0, 2]])

In [32]:
values[:, prices.argsort()]

array([[[ 20.,  60.,   3.]],

       [[ 50., 100.,   2.]],

       [[ 30., 120.,   4.]]])

In [30]:
prices = np.array(values[:, 0] / values[:, 1], ndmin=2)
print(prices)
values = np.append(values, prices.T, axis=1)
print(values)


[[3. 2. 4.]]
[[ 60.  20.   3.]
 [100.  50.   2.]
 [120.  30.   4.]]
