In [4]:
import numpy as np
import random

In [5]:
arr = np.array([i for i in range(0, 100, 2) for _ in range(3)])
print(arr)

[ 0  0  0  2  2  2  4  4  4  6  6  6  8  8  8 10 10 10 12 12 12 14 14 14
 16 16 16 18 18 18 20 20 20 22 22 22 24 24 24 26 26 26 28 28 28 30 30 30
 32 32 32 34 34 34 36 36 36 38 38 38 40 40 40 42 42 42 44 44 44 46 46 46
 48 48 48 50 50 50 52 52 52 54 54 54 56 56 56 58 58 58 60 60 60 62 62 62
 64 64 64 66 66 66 68 68 68 70 70 70 72 72 72 74 74 74 76 76 76 78 78 78
 80 80 80 82 82 82 84 84 84 86 86 86 88 88 88 90 90 90 92 92 92 94 94 94
 96 96 96 98 98 98]


In [6]:
def binary_search_loop(keys, query):
    start_idx, end_idx = 0, len(keys) - 1
    
    
    while(start_idx <= end_idx):
        mid_idx = (start_idx + end_idx)//2
        if(keys[mid_idx] < query): start_idx = mid_idx + 1
        elif(query < keys[mid_idx]): end_idx = mid_idx - 1
        else:
            return mid_idx
    
    return -1

In [7]:
#try doing it without including last query, just writing it down and slicing

def binary_search_loop_duplicates(keys, query):
    start_idx, end_idx = 0, len(keys) - 1
    
    
    while(start_idx <= end_idx):
        mid_idx = (start_idx + end_idx)//2
        if(keys[mid_idx] < query): start_idx = mid_idx + 1
        elif(query < keys[mid_idx]): end_idx = mid_idx - 1
        elif(query == keys[mid_idx] and (end_idx + 1) - start_idx > 1):
            end_idx = mid_idx
        else:
            return mid_idx
    
    return -1

In [8]:
def search_naive(keys, query):
    for idx in range(len(keys)):
        if(keys[idx] == query):
            return idx
    
    return -1

In [10]:
a = binary_search_loop_duplicates(arr, 4)
print(a)
search_naive(arr, 4)

6


6

In [12]:
import random
import time

# generate a large list of random integers with duplicates
keys = [random.randint(1, 1000000) for _ in range(100000)]

# sort the list in ascending order
keys.sort()

# select a random key to search for
query = random.choice(keys)

# measure the execution time of the binary search function
start_time = time.time()
result = binary_search_loop_duplicates(keys, query)
end_time = time.time()
print(f"Result: {result}")
print(f"Execution time: {end_time - start_time:.6f} seconds")
start_time = time.time()
result_naive = search_naive(keys, query)
end_time = time.time()
assert(result == result_naive)

# print the result and execution time
print(f"Result: {result}")
print(f"Execution time: {end_time - start_time:.6f} seconds")


Result: 11579
Execution time: 0.000057 seconds
Result: 11579
Execution time: 0.001332 seconds


In [50]:
def window_length(end_idx, start_idx):
    return (end_idx + 1) - start_idx

def majority_element(arr):
    arr = merge_sort(arr)
    
    max_window_length = 1
    current_window = 1
    for i in range(1, len(arr), 1):
        if arr[i-1] == arr[i]:
            current_window+=1
            
        else:
            if max_window_length < current_window:
                max_window_length = current_window
                current_window=1
        
    if max_window_length > len(arr) / 2: # > !,  n/2, n=2 = 1 max > 1
        return 1
    return 0
        
            
            

In [52]:
majority_element(keys)

0

In [58]:
len(arr) /2 

1.0

In [59]:
arr = [1, 1]
majority_element(arr)

0

In [19]:
def merge(left, right):
    seq = [0 for i in range(len(left) + len(right))]
    idx_min_left, idx_min_right = 0, 0
    
    for i in range(len(seq)):
        
        if(idx_min_left == len(left)):
            seq[i:len(seq)] = right[idx_min_right:len(right)]
            break
        elif(idx_min_right  == len(right)):
            seq[i:len(seq)] = left[idx_min_left:len(left)]
            break
        
        elif(left[idx_min_left] < right[idx_min_right]):
            seq[i] = left[idx_min_left]
            idx_min_left += 1
        else:
            seq[i] = right[idx_min_right]
            idx_min_right  += 1
    
    return seq


def merge_sort(seq):
    if len(seq) == 1: return seq
    left = merge_sort(seq[0:len(seq)//2])
    right = merge_sort(seq[len(seq)//2:len(seq)])
    seq = merge(left, right)
    return seq 

In [32]:
keys = [random.randint(1, 1000000) for _ in range(100000)]

In [37]:
keys_sorted = sorted(keys)

In [39]:
keys_sorted == merge_sort(keys)

True

In [40]:
import random

def test_merge_sort():


    # test with a list of length 1
    seq = [5]
    assert merge_sort(seq) == sorted(seq)

    # test with a list of length 2
    seq = [5, 3]
    assert merge_sort(seq) == sorted(seq)

    # test with a list of length 3
    seq = [5, 3, 8]
    assert merge_sort(seq) == sorted(seq)

    # test with a list of length 10
    seq = random.sample(range(100), 10)
    assert merge_sort(seq) == sorted(seq)

    # test with a list of length 100
    seq = random.sample(range(1000), 100)
    assert merge_sort(seq) == sorted(seq)

    # test with a list of length 1000
    seq = random.sample(range(10000), 1000)
    assert merge_sort(seq) == sorted(seq)

    print("All test cases pass")


# call the test function
test_merge_sort()


All test cases pass


#### Edge detection?

In [9]:


def binary_search_loop_end_detection(keys, query):
    start_idx, end_idx = 0, len(keys) - 1
    
    
    while(start_idx <= end_idx):
        mid_idx = (start_idx + end_idx)//2
        if keys[mid_idx] < query: start_idx = mid_idx + 1
        elif query < keys[mid_idx]: end_idx = mid_idx - 1
        
        elif query == keys[mid_idx]:
            if keys[mid_idx] == keys[end_idx]: return end_idx
            
            
            window_length = (end_idx + 1) - start_idx
            if window_length > 2: start_idx = mid_idx
            
            if window_length <= 2: return mid_idx
        
    return -1
            

In [16]:
def search_end_idx(keys, start):
    start_idx, end_idx = start, len(keys) - 1
    
    while(end_idx - start_idx > 1):
        mid_idx = (start_idx + end_idx) // 2
        if keys[start_idx] == keys[mid_idx]: start_idx = mid_idx
        elif keys[start_idx] < keys[mid_idx]: end_idx = mid_idx - 1
        
    
    return start_idx

In [17]:
def binary_search_loop_edges(keys, query):
    start = binary_search_loop_duplicates(keys, query)
    end = search_end_idx(keys[start:len(keys)], start)
    return [start, end]

In [13]:
arr

array([ 0,  0,  0,  2,  2,  2,  4,  4,  4,  6,  6,  6,  8,  8,  8, 10, 10,
       10, 12, 12, 12, 14, 14, 14, 16, 16, 16, 18, 18, 18, 20, 20, 20, 22,
       22, 22, 24, 24, 24, 26, 26, 26, 28, 28, 28, 30, 30, 30, 32, 32, 32,
       34, 34, 34, 36, 36, 36, 38, 38, 38, 40, 40, 40, 42, 42, 42, 44, 44,
       44, 46, 46, 46, 48, 48, 48, 50, 50, 50, 52, 52, 52, 54, 54, 54, 56,
       56, 56, 58, 58, 58, 60, 60, 60, 62, 62, 62, 64, 64, 64, 66, 66, 66,
       68, 68, 68, 70, 70, 70, 72, 72, 72, 74, 74, 74, 76, 76, 76, 78, 78,
       78, 80, 80, 80, 82, 82, 82, 84, 84, 84, 86, 86, 86, 88, 88, 88, 90,
       90, 90, 92, 92, 92, 94, 94, 94, 96, 96, 96, 98, 98, 98])

In [18]:
binary_search_loop_edges(arr, 2)

[3, 4]

In [12]:
def naive_edge_detection(keys, query):
    edges = [-1, -1]
    for idx in range(len(keys)):
        if((idx == 0 and keys[idx] == query) or (idx >= 1 and keys[idx] == query and keys[idx-1] != query)):
            edges[0] = idx
        if((idx == len(keys) - 1 and keys[idx] == query) or (idx < len(keys) - 1 and keys[idx] == query and keys[idx+1] != query)):
            edges[1] = idx
    return edges

In [5]:
def search_naive(keys, query):
    for idx in range(len(keys)):
        if(keys[idx] == query):
            return idx
    
    return -1

In [18]:
arr

array([ 0,  0,  0,  2,  2,  2,  4,  4,  4,  6,  6,  6,  8,  8,  8, 10, 10,
       10, 12, 12, 12, 14, 14, 14, 16, 16, 16, 18, 18, 18, 20, 20, 20, 22,
       22, 22, 24, 24, 24, 26, 26, 26, 28, 28, 28, 30, 30, 30, 32, 32, 32,
       34, 34, 34, 36, 36, 36, 38, 38, 38, 40, 40, 40, 42, 42, 42, 44, 44,
       44, 46, 46, 46, 48, 48, 48, 50, 50, 50, 52, 52, 52, 54, 54, 54, 56,
       56, 56, 58, 58, 58, 60, 60, 60, 62, 62, 62, 64, 64, 64, 66, 66, 66,
       68, 68, 68, 70, 70, 70, 72, 72, 72, 74, 74, 74, 76, 76, 76, 78, 78,
       78, 80, 80, 80, 82, 82, 82, 84, 84, 84, 86, 86, 86, 88, 88, 88, 90,
       90, 90, 92, 92, 92, 94, 94, 94, 96, 96, 96, 98, 98, 98])

In [30]:
naive_edge_detection(arr, 2)

[3, 5]

In [32]:
binary_search_loop_edges(arr, 2)

[3, 4]

In [6]:
binary_search_duplicates(arr, 8)

NameError: name 'binary_search_duplicates' is not defined

In [109]:
search_naive(arr, 8)

12

In [101]:
binary_search_loop(arr, 8)

p


4

In [117]:
def test_duplicates(keys, query):
    for q in range(1, query, 1):
        if(search_naive(keys, q) != binary_search_loop_duplicates(keys, q)):
            print(q)

In [141]:
test_duplicates(arr, 98)

In [111]:
def test_simple_binary_search(keys, query):
    for q in range(1, query, 1):
        if(search_naive(keys, q) != binary_search_loop(keys, q)):
            print(q)

In [185]:
def test_end_detection(keys, query):
    for q in range(1, query, 1):
        if(naive_edge_detection(keys, q)[1] != binary_search_loop_end_detection(keys, q)):
            print(q)

In [173]:
def test_naive_detection(keys, query):
    for q in range(1, query, 1):
        print(naive_edge_detection(keys, q))

In [181]:
binary_search_loop_end_detection(arr,18)

29

In [177]:
arr[27]

18

In [186]:
test_end_detection(arr, 98)

In [53]:
def binary_search_r(keys, query):
    mid_num = len(keys)//2
    mid_key = keys[mid_num]
    res = False
    
    if(len(keys) == 1 and mid_key != query):
        return False
    
    if(mid_key < query):
        res = binary_search_r(keys[mid_num:len(keys)], query)
    elif(mid_key > query):
        res = binary_search_r(keys[0:mid_num], query)
    elif(mid_key == query):
        return True
    
    return res
        

In [106]:
def binary_search_duplicates(keys, start, end, query):
    
    mid_num = len(keys)//2
    mid_key = keys[mid_num]
    res = -1
    
    if(len(keys) == 1 and mid_key != query):
        return -1
    
    if(mid_key < query):
        res = binary_search_duplicates(keys[mid_num:end], mid_num, end, query)
    elif(mid_key > query):
        res = binary_search_duplicates(keys[0:mid_num], 0, end-mid_num, query)
    elif(mid_key == query and len(keys) > 2):
        print("mid_num: ", mid_num)
        print("res", res)
        print("keys", keys)
        print("end", end)
        res = binary_search_duplicates(keys[0:(mid_num+1)], 0, end - mid_num + 1, query)
    elif(mid_key == query and len(keys) == 2):
        res = end-1
    
    return res
        

    

In [28]:
def binary_search_duplicates(keys, end, query):
    
    mid_num = len(keys)//2
    mid_key = keys[mid_num]
    res = -1
    
    if(mid_key == query and len(keys) == 2):
        res = end
    if(len(keys) == 1 and mid_key != query):
        return -1
    
    if(mid_key < query):
        res = binary_search_duplicates(keys[mid_num:len(keys)], end, query)
    elif(mid_key > query):
        res = binary_search_duplicates(keys[0:mid_num], end - mid_num, query)
    elif(mid_key == query and len(keys) > 2):
        res = binary_search_duplicates(keys[0:(mid_num+1)], end - mid_num, query)
    elif(mid_key == query and len(keys) == 2):
        res = end
    
    return res
        

    

In [78]:
def binary_search_duplicates(keys, last_idx, query):
    mid_num = len(keys)//2
    mid_key = keys[mid_num]
    res = -1
    
    if(mid_key == query and len(keys) == 2):
        res = last_idx
        
    elif(len(keys) == 1):
        return -1
    
    if(mid_key < query):
        res = binary_search_duplicates(keys[mid_num+1:len(keys)], last_idx, query)
    elif(mid_key > query):
        res = binary_search_duplicates(keys[0:mid_num+1], last_idx+1 - mid_num, query)
    elif(mid_key == query and len(keys) > 1):
        res = binary_search_duplicates(keys[0:mid_num+1], last_idx+1 - mid_num, query)
    elif(mid_key == query and len(keys) == 1):
        res = last_idx
    
    if(mid_key < query):
        res = binary_search_duplicates(keys[mid_num+1 : len(keys)], query)
    elif(mid_key > query):
        res = binary_search_duplicates(keys[0 : mid_num+1], query)
    return res

In [77]:
def binary_search(keys, query):
    mid_num = len(keys)//2
    mid_key = keys[mid_num]
    
    
    if(mid_key == query):
        return 1
    elif(len(keys) == 1):
        return -1
    
    if(mid_key < query):
        res = binary_search(keys[mid_num+1 : len(keys)], query)
    elif(mid_key > query):
        res = binary_search(keys[0 : mid_num+1], query)
    return res
    
    
    

In [2]:
2**32

4294967296

In [4]:
9*10**10

90000000000

In [1]:
10**9

1000000000

In [18]:
def naive_search_duplicates(keys, queries):
    
    for query in queries:
        for key_num in range(len(keys)):
            if keys[key_num] == query:
                return key_num
            
    else: 
        return -1

In [152]:
def binary_search_q(keys, query):
    res = [-1 for i in range(len(query))]
    for i in range(len(query)):
        res[i] = i if binary_search(keys, query[i]) else -1
    return res

        

In [35]:
arr2 = [i for i in range(9) for _ in range(3)]
arr1 = [i for i in range(17, 0, -1) for _ in range(2)]

In [36]:
type(arr1)

list

In [37]:
print(arr1)

[17, 17, 16, 16, 15, 15, 14, 14, 13, 13, 12, 12, 11, 11, 10, 10, 9, 9, 8, 8, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1, 1]


In [38]:
arr1_sort = merge_sort(arr1)
print(arr1_sort)

[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16, 17, 17]


In [18]:
arr_merge = merge(arr1, arr2)

In [21]:
print(arr1, "\n", arr2)

[5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16] 
 [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8]


In [20]:
print(arr_merge)

[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16]


In [46]:
import random

In [51]:

# just use swap instead dynamic array
def quicksort(seq):
    if len(seq) == 1: 
        return seq
    
    new_seq, left, right = [], [], []    #dynamic arrays also nlog(n)
    partition_idx = random.randint(0, len(seq))
    for i in range(len(seq)):
        if seq[partition_idx] > seq[i]:
            left.append(seq[i])
        else: right.append(seq[i])
        
    new_seq.append(quicksort(left))
    new_seq.append(seq[partition_idx])
    new_seq.append(quicksort(right))
    
    return new_seq

In [ ]:
def quicksort(seq):
    partition_idx = random.randint(0, len(seq))
    
    for i in range(len(seq)):
        if seq[partition_idx]

In [55]:
arr1.append([12,1234,124])
print(arr1)

[17, 17, 16, 16, 15, 15, 14, 14, 13, 13, 12, 12, 11, 11, 10, 10, 9, 9, 8, 8, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2, 1, 1, [12, 1234, 124], [12, 1234, 124]]


In [52]:
quicksort(arr1)

IndexError: list index out of range

In [1]:
import numpy as np

In [8]:
def edit_distance(first_string, second_string):
    dp_table = np.zeros((len(first_string)+1, len(second_string) + 1))
    
    for i in range(dp_table.shape[0]):
        for j in range(dp_table.shape[1]):
            if i == 0 and j == 0:
                dp_table[i, j] = 0
            elif i == 0:
                dp_table[i, j] = dp_table[i, j-1] + 1
            elif j == 0:
                dp_table[i, j] = dp_table[i-1, j] + 1
            else:
                
    return dp_table

In [9]:
edit_distance("suck", "ass")

array([[0., 1., 2., 3.],
       [1., 0., 0., 0.],
       [2., 0., 0., 0.],
       [3., 0., 0., 0.],
       [4., 0., 0., 0.]])

In [10]:
edit_distance("editing", "distance")

array([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [6., 0., 0., 0., 0., 0., 0., 0., 0.],
       [7., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [2]:
a = "ab"

In [4]:
len(a)

2